"""
extract_neso_window.py
======================

Extract a 360-second frequency-trajectory window from a NESO Historic
Frequency CSV and emit BOTH artefacts needed to reproduce a bench replay:

    - neso_trajectory_<label>.h    ESP32 flash file (drops into Feather 2
                                    build folder as neso_trajectory.h)
    - neso_trajectory_<label>.csv  analysis input for run_live_verification.py
                                    (--neso argument)

The chosen window is centred on the point of maximum |f - 50 Hz| deviation,
with 120 samples of pre-context (matching the Aug 2019 canonical window
convention where the nadir sits at index 120).

Two selection modes:

    --auto           (default) find the maximum-deviation point automatically
    --start T        force the window to start at ISO timestamp T
                     (e.g. --start "2023-12-22 13:06:11")

USAGE

    python extract_neso_window.py NESOcsv.csv --label December2023Peak
    python extract_neso_window.py NESOcsv.csv --label MyEvent --start "2019-08-09 16:51:49"

INPUT CSV FORMAT (matches the NESO Historic Frequency dataset)

    dtm,f
    2023-12-01 00:00:00,50.099
    2023-12-01 00:00:01,50.089
    ...

OUTPUT .h FORMAT is byte-compatible with the existing feather_2_code_mimoDEMO.ino:
if you rename the output to neso_trajectory.h in the build folder, the
firmware picks it up without any code change.

Author: Jack Davies
"""

from __future__ import annotations
import argparse, csv, os, sys
from datetime import datetime

WINDOW_LEN = 360      # 360 one-second samples = the paper's canonical window length
PRE_CONTEXT = 120     # samples of pre-event context (nadir at index 120 convention)


def parse_dtm(s: str) -> datetime:
    """Parse a NESO dtm string, tolerating with/without timezone."""
    s = s.strip().replace('+0000', '').replace('+0100', '').strip()
    # try a few tolerant formats
    for fmt in ('%Y-%m-%d %H:%M:%S', '%Y-%m-%dT%H:%M:%S'):
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue
    raise ValueError(f"Cannot parse dtm: {s!r}")


def load_csv(path: str):
    dtms = []
    fs = []
    with open(path, newline='') as fh:
        rdr = csv.DictReader(fh)
        for row in rdr:
            dtms.append(row['dtm'])
            fs.append(float(row['f']))
    return dtms, fs


def find_max_dev_index(fs) -> int:
    best = 0
    best_dev = 0.0
    for i, f in enumerate(fs):
        d = abs(f - 50.0)
        if d > best_dev:
            best_dev = d
            best = i
    return best


def find_start_by_time(dtms, target_str: str) -> int:
    target = parse_dtm(target_str)
    for i, d in enumerate(dtms):
        if parse_dtm(d) >= target:
            return i
    raise ValueError(f"Timestamp {target_str} not in file")


def rocof(fs):
    """1-sample forward diff (Hz per sample = Hz/s at 1 Hz sample rate)."""
    return [fs[i+1] - fs[i] for i in range(len(fs)-1)]


def write_header(path: str, label: str, window_fs, window_dtms, nadir_idx: int):
    max_rocof = max(abs(r) for r in rocof(window_fs))
    src_start = window_dtms[0]
    src_end = window_dtms[-1]
    nadir_f = window_fs[nadir_idx]
    with open(path, 'w', newline='\n') as fh:
        fh.write(f"""\
// SPDX-License-Identifier: MIT
// NESO {label} frequency trajectory
// Source: NESO Historic Frequency dataset, 1-second resolution
// Window: {src_start} to {src_end}
// Nadir/peak: {nadir_f:.3f} Hz at index {nadir_idx} (t = {nadir_idx - PRE_CONTEXT} s in replay clock)
// Max |RoCoF|: {max_rocof:.4f} Hz/s
//
// Auto-generated by extract_neso_window.py — do not hand-edit.

#ifndef NESO_TRAJECTORY_H
#define NESO_TRAJECTORY_H

#include <stdint.h>

static const uint16_t NESO_TRAJECTORY_LENGTH = {WINDOW_LEN};
static const uint16_t NESO_NADIR_INDEX       = {nadir_idx};
static const float    NESO_NADIR_FREQUENCY   = {nadir_f:.3f}f;  // Hz

// ESP32 places 'const' arrays in flash (.rodata) automatically.
// Access with NESO_TRAJECTORY[i] directly — no pgm_read_float needed.
static const float NESO_TRAJECTORY[NESO_TRAJECTORY_LENGTH] = {{
""")
        for f in window_fs:
            fh.write(f"  {f:.3f}f,\n")
        fh.write("""\
};

#endif // NESO_TRAJECTORY_H
""")


def write_csv(path: str, window_fs, window_dtms):
    with open(path, 'w', newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['t_s', 'dtm', 'f_neso_Hz'])
        for i, (dtm, f) in enumerate(zip(window_dtms, window_fs)):
            w.writerow([i, dtm.strip(), f'{f:.3f}'])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('csv_path', help='NESO Historic Frequency CSV')
    ap.add_argument('--label', required=True,
        help='Short event label (e.g. December2023Peak) — used in output filenames and header')
    ap.add_argument('--start', default=None,
        help='ISO timestamp to force window start; default is auto-select at max |f - 50 Hz|')
    ap.add_argument('--outdir', default='.',
        help='Output directory (default: current)')
    ap.add_argument('--pre-context', type=int, default=PRE_CONTEXT,
        help=f'Samples of pre-event context (default: {PRE_CONTEXT})')
    args = ap.parse_args(argv)

    print(f"Loading {args.csv_path} ...", file=sys.stderr)
    dtms, fs = load_csv(args.csv_path)
    print(f"  {len(fs)} samples loaded", file=sys.stderr)

    # Choose the window centre
    if args.start:
        window_start = find_start_by_time(dtms, args.start)
        event_idx = window_start + args.pre_context
    else:
        event_idx = find_max_dev_index(fs)
        window_start = max(0, event_idx - args.pre_context)

    window_end = min(len(fs), window_start + WINDOW_LEN)
    window_start = max(0, window_end - WINDOW_LEN)  # backtrack if we hit the end
    window_fs = fs[window_start:window_end]
    window_dtms = dtms[window_start:window_end]
    nadir_idx = event_idx - window_start
    if nadir_idx < 0 or nadir_idx >= WINDOW_LEN:
        # window doesn't contain the event (shouldn't happen with sane inputs)
        nadir_idx = window_fs.index(min(window_fs, key=lambda x: abs(x - 50.0)))

    print(f"  Window: {window_dtms[0]} to {window_dtms[-1]}", file=sys.stderr)
    print(f"  Event/nadir at index {nadir_idx} (f = {window_fs[nadir_idx]:.3f} Hz)", file=sys.stderr)
    print(f"  Max |f - 50 Hz|: {max(abs(f - 50) for f in window_fs)*1000:.1f} mHz", file=sys.stderr)
    print(f"  Max |RoCoF|:     {max(abs(r) for r in rocof(window_fs)):.4f} Hz/s", file=sys.stderr)

    os.makedirs(args.outdir, exist_ok=True)
    h_path   = os.path.join(args.outdir, f'neso_trajectory_{args.label}.h')
    csv_path = os.path.join(args.outdir, f'neso_trajectory_{args.label}.csv')
    write_header(h_path, args.label, window_fs, window_dtms, nadir_idx)
    write_csv(csv_path, window_fs, window_dtms)
    print(f"  Wrote {h_path}", file=sys.stderr)
    print(f"  Wrote {csv_path}", file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
